version: "3.9"
services:
  enrolled-payment-instrument:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=test-db
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
      - KAFKA_BROKER=kafka:29095
    networks:
      - internal-net
    depends_on:
      - kafka
      - db

  # external services
  db:
    image: 'bitnami/postgresql:latest'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=test-db
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
    networks:
      - internal-net

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      - internal-net

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "29095:29095"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
    networks:
      - internal-net
    depends_on:
      - zookeeper

networks:
  internal-net:
    driver: bridge