logging:
  level:
    root: INFO

spring:
  config:
      activate:
        on-profile: default
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: ${POSTGRES_SHOW_SQL:true}
    hibernate.ddl-auto: none

  datasource:
    url: ${POSTGRES_CONN_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:}}
    username: ${POSTGRES_USERNAME:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  cloud:
    stream:
      bindings:
        enrolledPaymentInstrumentConsumer-in-0:
          destination: rtd-platform-events
          group: rtd-enrolled-payment-instrument-consumer-group
          content-type: application/json
          binder: kafka-binder

      binders:
        kafka-binder:
          type: kafka
          environment:
            spring.cloud.stream.kafka:
              binder:
                auto-create-topics: false
                brokers: ${KAFKA_BROKER:localhost:29095}
                consumerProperties:
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer