logging:
  level:
    root: INFO

spring:
  config:
      activate:
        on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}

  cloud:
    stream:
      bindings:
        enrolledPaymentInstrumentConsumer-in-0:
          destination: ${KAFKA_TOPIC_EVENTS:rtd-enrolled-events}
          group: rtd-enrolled-payment-instrument-consumer-group
          content-type: application/json
          binder: kafka-binder
          consumer: # configure consumer to retry to process and event when WriteConflict happens
            defaultRetryable: false
            retryableExceptions:
              it.gov.pagopa.rtd.ms.enrolledpaymentinstrument.infrastructure.persistence.exception.WriteConflict: true

      binders:
        kafka-binder:
          type: kafka
          environment:
            spring.cloud.stream.kafka:
              binder:
                auto-create-topics: false
                brokers: ${KAFKA_BROKER:localhost:29095}
                configuration:
                  sasl:
                    jaas.config: ${KAFKA_SASL_JAAS_CONFIG_CONSUMER_ENROLLED_PI}
                    mechanism: PLAIN
                  security.protocol: SASL_SSL
                consumerProperties:
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer