apiVersion: v2
name: rtd-ms-enrolled-payment-instrument
description: Micro-service designed to manage the payment instruments enrolled from applications
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"