microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/rtdmsenrolledpaymentinstrument
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.rtd.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  envConfig:
    IMMEDIATE_CONFIRM_EXPORT: "false"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url

  #  autoscaling:
  #    enable: false
  #    minReplica: 1
  #    maxReplica: 2
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: azure-monitor
  #        metadata:
  #          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
  #          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
  #          resourceGroupName: dvopla-d-sec-rg
  #          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
  #          metricName: ServiceApiHit
  #          # metricNamespace: Microsoft.KeyVault/vaults
  #          # metricFilter: namespace eq 'default'
  #          # metricAggregationInterval: "-1:1:0"
  #          metricAggregationType: Count
  #          targetValue: "30"

  keyvault:
    name: "cstar-u-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
