apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtd-ms-enrolledpaymentinstrument
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtd-ms-enrolledpaymentinstrument
  template:
    metadata:
      labels:
        app: rtd-ms-enrolledpaymentinstrument
    spec:
      containers:
        - name: rtd-ms-enrolledpaymentinstrument
          image: rtd-ms-enrolledpaymentinstrument
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rtd-enrolled-pi-events
            - secretRef:
                name: mongo-credentials
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi